# Generated by Django 3.1.4 on 2020-12-23 11:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='about',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intro', models.TextField(default='')),
                ('image', models.ImageField(blank=True, default='', null=True, upload_to='media')),
            ],
        ),
        migrations.CreateModel(
            name='announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default='')),
                ('image', models.ImageField(blank=True, default='', null=True, upload_to='media')),
                ('file', models.FileField(blank=True, default='', null=True, upload_to='files')),
                ('pub_date', models.DateField(default=django.utils.timezone.now)),
                ('time', models.TimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-pub_date', '-time'],
            },
        ),
        migrations.CreateModel(
            name='certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=80)),
                ('Description', models.CharField(default='', max_length=120)),
                ('image', models.ImageField(default='default.jpg', upload_to='media')),
                ('file', models.FileField(default='', upload_to='certificates')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-pub_date'],
            },
        ),
        migrations.CreateModel(
            name='director',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=500)),
                ('text', models.TextField(default='')),
                ('image', models.ImageField(default='', upload_to='media')),
            ],
        ),
        migrations.CreateModel(
            name='event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=1500)),
                ('description', models.TextField(default='')),
                ('venue', models.CharField(default='', max_length=5000)),
                ('date', models.DateField()),
                ('time', models.TimeField(blank=True, default='', null=True)),
            ],
            options={
                'ordering': ['-date', 'time'],
            },
        ),
        migrations.CreateModel(
            name='faq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(default='')),
                ('answer', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=500)),
                ('email', models.CharField(default='', max_length=1000)),
                ('subject', models.CharField(default='', max_length=1500)),
                ('message', models.TextField(default='')),
                ('posting_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='', upload_to='gallery')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-pub_date'],
            },
        ),
        migrations.CreateModel(
            name='guideline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='img_slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='', upload_to='gallery')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-pub_date'],
            },
        ),
        migrations.CreateModel(
            name='innovation',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=1500)),
                ('description', models.TextField(default='')),
                ('thumbnail', models.ImageField(default='', upload_to='media')),
                ('image', models.ImageField(blank=True, default='', null=True, upload_to='study')),
                ('file', models.FileField(blank=True, default='', null=True, upload_to='study')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-pub_date'],
            },
        ),
        migrations.CreateModel(
            name='pcategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat', models.CharField(default='', max_length=1500)),
            ],
        ),
        migrations.CreateModel(
            name='psubcategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcat', models.CharField(default='', max_length=1500)),
            ],
        ),
        migrations.CreateModel(
            name='sop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=80)),
                ('Description', models.CharField(default='', max_length=120)),
                ('image', models.ImageField(default='default.jpg', upload_to='media')),
                ('file', models.FileField(default='', upload_to='sops')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-pub_date'],
            },
        ),
        migrations.CreateModel(
            name='staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=500)),
                ('designation', models.CharField(default='', max_length=1000)),
                ('contact', models.CharField(default='', max_length=1500)),
            ],
        ),
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(default='', max_length=1500)),
                ('title', models.CharField(default='', max_length=1500)),
                ('description', models.TextField(default='')),
                ('thumbnail', models.ImageField(default='', upload_to='media')),
                ('image', models.ImageField(blank=True, default='', null=True, upload_to='projects')),
                ('file', models.FileField(blank=True, default='', null=True, upload_to='projects')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('category', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='main.pcategory')),
                ('subcategory', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='main.psubcategory')),
            ],
            options={
                'ordering': ['-pub_date'],
            },
        ),
    ]
