# Generated by Django 3.1.4 on 2020-12-23 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20201223_2126'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='image',
            new_name='images',
        ),
    ]
