# Generated by Django 3.1.4 on 2020-12-23 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_faq_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='answer',
            field=models.TextField(default=''),
        ),
    ]
