# Generated by Django 3.1.4 on 2020-12-25 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_faq_answer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-eventdate', 'time']},
        ),
        migrations.RenameField(
            model_name='event',
            old_name='date',
            new_name='eventdate',
        ),
    ]
