# Generated by Django 3.1.4 on 2021-01-09 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20201226_0117'),
    ]

    operations = [
        migrations.DeleteModel(
            name='innovation',
        ),
        migrations.RenameField(
            model_name='director',
            old_name='image',
            new_name='images',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='images',
        ),
        migrations.RemoveField(
            model_name='project',
            name='category',
        ),
        migrations.RemoveField(
            model_name='project',
            name='images',
        ),
        migrations.RemoveField(
            model_name='project',
            name='subcategory',
        ),
        migrations.RemoveField(
            model_name='project',
            name='thumbnail',
        ),
        migrations.RemoveField(
            model_name='sop',
            name='images',
        ),
        migrations.AddField(
            model_name='director',
            name='designation',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='gallery',
            name='caption',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='img_slider',
            name='caption',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='intro',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='Description',
            field=models.CharField(blank=True, default='', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='author',
            field=models.CharField(blank=True, default='', max_length=1500, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='sop',
            name='Description',
            field=models.CharField(blank=True, default='', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='contact',
            field=models.CharField(blank=True, default='', max_length=1500, null=True),
        ),
        migrations.DeleteModel(
            name='pcategory',
        ),
        migrations.DeleteModel(
            name='psubcategory',
        ),
    ]
