# Generated by Django 3.1.4 on 2021-01-18 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20210109_2315'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('synopsis', 'Synopsis '), ('nonsynopsis', 'Non-Synopsis ')], default='', max_length=150),
        ),
        migrations.AddField(
            model_name='project',
            name='subcategory',
            field=models.CharField(choices=[('categorya', 'Category A'), ('categoryb', 'Category B'), ('categoryc', 'Category C'), ('categorybc', 'Category B/C')], default='', max_length=150),
        ),
    ]
