# Generated by Django 3.1.4 on 2021-01-21 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20210119_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='subcategory',
            field=models.CharField(choices=[('categorya', 'Category A'), ('categoryb', 'Category B'), ('categoryc', 'Category C'), ('categorybc', 'CategoryB/C')], default='', max_length=150),
        ),
    ]
